name: Anchor Build (wheel8)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check repo contents
        shell: bash
        run: |
          echo "PWD=$(pwd)"
          echo "Top-level contents:"
          ls -la
          echo "----"
          if [ -d wheel8 ]; then
            echo "wheel8/ folder found ✅"
            ls -la wheel8
          else
            echo "wheel8/ folder NOT FOUND ❌"
          fi

      - name: Detect Anchor project dir
        id: finddir
        shell: bash
        run: |
          if [ -f Anchor.toml ]; then
            echo "project_dir=." >> "$GITHUB_OUTPUT"
          elif [ -f wheel8/Anchor.toml ]; then
            echo "project_dir=wheel8" >> "$GITHUB_OUTPUT"
          else
            echo "No Anchor.toml at repo root or in wheel8/"
            ls -la
            exit 1
          fi

      - name: Show project dir tree
        shell: bash
        run: |
          echo "Project dir: ${{ steps.finddir.outputs.project_dir }}"
          ls -la "${{ steps.finddir.outputs.project_dir }}"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Verify Anchor via npx
        shell: bash
        run: npx --yes @coral-xyz/anchor@latest --version

      - name: Build Anchor program (npx)
        shell: bash
        run: |
          cd "${{ steps.finddir.outputs.project_dir }}"
          npx --yes @coral-xyz/anchor@latest build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel8-artifacts
          path: |
            ${{ steps.finddir.outputs.project_dir }}/target/deploy/*
            ${{ steps.finddir.outputs.project_dir }}/target/idl/*
