name: Anchor Build (wheel8)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Anchor project dir
        id: finddir
        shell: bash
        run: |
          if [ -f Anchor.toml ]; then
            echo "project_dir=." >> "$GITHUB_OUTPUT"
          elif [ -f wheel8/Anchor.toml ]; then
            echo "project_dir=wheel8" >> "$GITHUB_OUTPUT"
          else
            echo "No Anchor.toml at repo root or in wheel8/"
            ls -la
            exit 1
          fi

      - name: Show repo tree
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "----"
          ls -la "${{ steps.finddir.outputs.project_dir }}"

      - name: Set up Node (for Anchor CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Anchor CLI
        run: |
          npm i -g @coral-xyz/anchor@latest
          # ensure npm's global bin is on PATH for subsequent steps
          echo "$(npm bin -g)" >> $GITHUB_PATH
          echo "NPM global bin: $(npm bin -g)"

      - name: Verify Anchor in PATH
        run: |
          which anchor || true
          anchor --version

      - name: Cache cargo & sbf
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cache/sbf
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Anchor program
        working-directory: ${{ steps.finddir.outputs.project_dir }}
        run: |
          anchor build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel8-artifacts
          path: |
            ${{ steps.finddir.outputs.project_dir }}/target/deploy/*
            ${{ steps.finddir.outputs.project_dir }}/target/idl/*
