name: Anchor Build (wheel8)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node (for Anchor CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Anchor CLI
        run: npm i -g @coral-xyz/anchor

      # Optional: speed up repeated builds by caching cargo/registry & SBF toolchain
      - name: Cache cargo & sbf
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cache/sbf
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Anchor program
        working-directory: ./wheel8
        run: |
          anchor --version
          anchor build

      - name: Upload deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel8-artifacts
          path: |
            wheel8/target/deploy/*
            wheel8/target/idl/*

