name: Anchor Build (wheel8)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check repo
        shell: bash
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "----"
          if [ -d wheel8 ]; then
            echo "wheel8/ found ✅"; ls -la wheel8
          else
            echo "wheel8/ NOT FOUND ❌ (ok if project is at repo root)"
          fi

      - name: Detect Anchor project dir
        id: finddir
        shell: bash
        run: |
          if [ -f Anchor.toml ]; then
            echo "project_dir=." >> "$GITHUB_OUTPUT"
          elif [ -f wheel8/Anchor.toml ]; then
            echo "project_dir=wheel8" >> "$GITHUB_OUTPUT"
          else
            echo "No Anchor.toml found at repo root or in wheel8/"
            ls -la
            exit 1
          fi

      - name: Show project dir tree
        shell: bash
        run: |
          echo "Project dir: ${{ steps.finddir.outputs.project_dir }}"
          ls -la "${{ steps.finddir.outputs.project_dir }}"

      - name: Install system build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev libudev-dev

      - name: Set up Rust (stable)
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustc --version || true

      # Anchor deps require Node >= 20.18.0
      - name: Set up Node (>=20.18)
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'

      # Install Anchor LOCALLY inside the project dir and call the local bin explicitly
      - name: Install local Anchor CLI
        shell: bash
        working-directory: ${{ steps.finddir.outputs.project_dir }}
        run: |
          set -euxo pipefail
          node -v
          npm -v
          # Create a minimal package.json if none exists
          test -f package.json || npm init -y
          # Install Anchor as a local dependency
          npm install --no-audit --no-fund @coral-xyz/anchor@latest
          # Show where the local binary lives
          ls -la node_modules/.bin || true
          ./node_modules/.bin/anchor --version

      - name: Cache cargo & sbf
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cache/sbf
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Anchor program (verbose, local bin)
        shell: bash
        working-directory: ${{ steps.finddir.outputs.project_dir }}
        run: |
          set -euxo pipefail
          echo "Using Anchor.toml from: $(pwd)"
          sed -n '1,160p' Anchor.toml || true
          ./node_modules/.bin/anchor build --verbose 2>&1 | tee build.log

      - name: Upload artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: wheel8-artifacts
          path: |
            ${{ steps.finddir.outputs.project_dir }}/target/deploy/*
            ${{ steps.finddir.outputs.project_dir }}/target/idl/*
            ${{ steps.finddir.outputs.project_dir }}/build.log
